package com.atovio.mybatis.mapper;

import com.atovio.mybatis.pojo.Car;
import com.atovio.mybatis.pojo.CarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    long countByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int deleteByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int insert(Car row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int insertSelective(Car row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    List<Car> selectByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    Car selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int updateByExampleSelective(@Param("row") Car row, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int updateByExample(@Param("row") Car row, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int updateByPrimaryKeySelective(Car row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    int updateByPrimaryKey(Car row);
}