package com.atovio.mybatis.pojo;

import java.math.BigDecimal;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.id
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.car_num
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    private String carNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.brand
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.guide_price
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    private BigDecimal guidePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.produce_time
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    private String produceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.car_type
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    private String carType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.id
     *
     * @return the value of t_car.id
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.id
     *
     * @param id the value for t_car.id
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.car_num
     *
     * @return the value of t_car.car_num
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.car_num
     *
     * @param carNum the value for t_car.car_num
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum == null ? null : carNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.brand
     *
     * @return the value of t_car.brand
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.brand
     *
     * @param brand the value for t_car.brand
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.guide_price
     *
     * @return the value of t_car.guide_price
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public BigDecimal getGuidePrice() {
        return guidePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.guide_price
     *
     * @param guidePrice the value for t_car.guide_price
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public void setGuidePrice(BigDecimal guidePrice) {
        this.guidePrice = guidePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.produce_time
     *
     * @return the value of t_car.produce_time
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public String getProduceTime() {
        return produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.produce_time
     *
     * @param produceTime the value for t_car.produce_time
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public void setProduceTime(String produceTime) {
        this.produceTime = produceTime == null ? null : produceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.car_type
     *
     * @return the value of t_car.car_type
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.car_type
     *
     * @param carType the value for t_car.car_type
     *
     * @mbg.generated Fri May 12 11:59:58 CST 2023
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }
}